model_name_or_path: /root/autodl-tmp/LLaMA-Factory/models/Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
quantization_bit: 4

dataset: law_qa_p3_b_engineered_500
template: qwen
cutoff_len: 512
max_samples: 120
overwrite_cache: true
preprocessing_num_workers: 8

output_dir: /root/autodl-tmp/saves/p4_lr_2e4
logging_steps: 5
save_steps: 4000
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 0.3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
max_grad_norm: 1.0

val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 20
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false