model_name_or_path: /root/autodl-tmp/LLaMA-Factory/models/Qwen/Qwen2.5-7B-Instruct


### 微调方法
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### QLoRA 量化
quantization_bit: 4

### 数据集
dataset: law_qa_alpaca
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### 输出
output_dir: /root/autodl-tmp/saves/law_qa_qlora_sft
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### 训练参数
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
max_grad_norm: 1.0

### 验证
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50
